#server:
#  port: 9091
#eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://mysql-db.c7g6ki2q2duj.ap-south-2.rds.amazonaws.com:3306/usersdb
    password: Hsenidbhu1
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


